Repository coala/coala-vs-code, pull requests merged in 2018-06, with the labels that each got.

#69 Use gitignore moban
  .ci/check_moban.sh
  .gitignore
  .moban.yaml
  .travis.yml
Labels: process/pending review, size/M

#71 .gitignore: Sync moban
  .gitignore
Labels: process/pending review, size/XS

#68 langserver.feature: Fix features of behaviour tests
  tests/server.features/langserver.feature
  tests/server.features/steps/langserver_steps.py
Labels: difficulty/low, difficulty/newcomer, importance/low, process/approved, size/XS, type/enhancement

#72 .rultor.yml: Remove unused config
  .rultor.yml
Labels: process/pending review, size/XS
