Repository coala/coala-vs-code, pull requests merged in 2018-08, with the labels that each got.

#75 .gitignore: moban sync
  .gitignore
Labels: process/pending review, size/XS

#78 langserver.py: Drop unused module
  coala_langserver/langserver.py
Labels: difficulty/newcomer, importance/low, process/approved, size/XS, type/style

#76 Update lang list in coala-vs-code plugin.
  src/extension.ts
Labels: process/approved, size/XS
